name: "Run Command In Arch Linux Docker"
description: "Wrapper for ghcr.io/dystopianos/arch-run-cmd"
author: "DCx7c5"

inputs:
  command:
    description: "Command/script to execute inside container"
    required: true
  working-directory:
    description: "Working directory inside container"
    required: false
    default: ""
  gpg-home:
    description: "GPG home directory"
    required: false
    default: ""
  ccache-dir:
    description: "ccache directory"
    required: false
    default: ""
  enable-ccache:
    description: "Enable ccache"
    required: false
    default: "true"
  gh-token:
    description: "GitHub token for API access"
    required: false
    default: ""
  gpg-key-id:
    description: "GPG key ID/fingerprint"
    required: false
    default: ""
  gpg-keygrips:
    description: "GPG keygrips"
    required: false
    default: ""
  gpg-passphrase:
    description: "GPG passphrase"
    required: false
    default: ""
  preset-passphrase-cache:
    description: "Preset passphrase cache"
    required: false
    default: "false"
  run-with-sudo:
    description: "Run command with sudo inside container"
    required: false
    default: "false"

runs:
  using: docker
  image: docker://ghcr.io/dystopianos/arch-run-cmd:latest
  env:
    GH_TOKEN: "${{ inputs.gh-token }}"
    GNUPGHOME: "${{ inputs.gpg-home }}"
    CCACHE_DIR: "${{ inputs.ccache-dir }}"
    WORKING_DIR: "${{ inputs.working-directory }}"
    RUN_WITH_SUDO: "${{ inputs.run-with-sudo }}"
    GPG_KEY_ID: "${{ inputs.gpg-key-id }}"
    GPG_PASSPHRASE: "${{ inputs.gpg-passphrase }}"
    PRESET_CACHE: "${{ inputs.preset-passphrase-cache }}"
    KEYGRIPS: "${{ inputs.gpg-keygrips }}"
  args:
    - ${{ inputs.command }}
